### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Quod6** [Quod6/ddz-tpro#2]
Сюда в комменты Митяй и Коля будут скидывать все, что они нарисовали, и мы вместе будем решать, мб надо что-то изменить или вообще нарисовать с 0

**Comment by Dmitriyyolo** [comment]
![Пример фона](https://user-images.githubusercontent.com/55884664/141657282-d2c013b2-2aa1-43ea-9c29-301cd8b441ba.jpg)

**Comment by Dmitriyyolo** [comment]
![rs-docs-2-bg](https://user-images.githubusercontent.com/55884664/141658289-38382018-740f-4887-b823-1bcf7bc1637f.png)

**Comment by Dmitriyyolo** [comment]
![Тестовая карта](https://user-images.githubusercontent.com/55884664/141659079-0fdb3a67-bf24-4c6c-a472-1bc0bb43a842.png)

**Comment by Dmitriyyolo** [comment]
![Тестовая желтая](https://user-images.githubusercontent.com/55884664/141659390-24638df5-41a4-4b4d-befd-896c3d9704a7.png)

**Comment by Dmitriyyolo** [comment]
![По заданию](https://user-images.githubusercontent.com/55884664/141659487-cf9bd8e1-e05d-4217-9cea-e28c57e4caf9.png)

**Comment by Dmitriyyolo** [comment]
Вот такая желто-оранжевая должна быть по заданию, но мне кажется в темно-синей стилистике будет покруче смотреться, че думаете?

**Comment by Quod6** [comment]
> Вот такая желто-оранжевая должна быть по заданию, но мне кажется в темно-синей стилистике будет покруче смотреться, че думаете?

На желтом фоне плохо видно бота

**Comment by CitizenFourCF4** [comment]
![menu](https://user-images.githubusercontent.com/94146075/141659885-5c8ce8e6-7f63-4f3d-a0a8-ac5cda0d7e45.png)
![menu1](https://user-images.githubusercontent.com/94146075/141659887-4d7663cf-6548-4bcf-af49-8e67727de759.png)

**Comment by IlyaSholokhov** [comment]
А почему на главном окне такое большое расстояние между setup и exit. Может setup сделать в виде шестеренки в каком-нибудь из углов?

**Comment by CitizenFourCF4** [comment]
сейчас будет

**Comment by CitizenFourCF4** [comment]
![begin](https://user-images.githubusercontent.com/94146075/141660159-90e10cb1-7c3b-4201-afad-cb58cd2174e9.png)

**Comment by CitizenFourCF4** [comment]
![final](https://user-images.githubusercontent.com/94146075/141661382-9e8d7675-cf39-42d3-a0f9-ef791fb5bdfd.png)

**Comment by CitizenFourCF4** [comment]
![new](https://user-images.githubusercontent.com/94146075/141682769-e02c56a4-ac93-405d-ab46-96fdb5fcf02e.png)

**Comment by CitizenFourCF4** [comment]
[141657282-d2c013b2-2aa1-43ea-9c29-301cd8b441ba.zip](https://github.com/Quod6/ddz-tpro/files/7533808/141657282-d2c013b2-2aa1-43ea-9c29-301cd8b441ba.zip)

**Comment by Quod6** [comment]
![colors](https://user-images.githubusercontent.com/36698256/141692762-1ba7396b-1b4d-43be-ac82-ddf69a586c36.jpg)

![buttons_v2](https://user-images.githubusercontent.com/36698256/141692764-214d0712-ec66-4617-b7e1-dd08c9925475.png)

Тк в фильме использовались цвета как на 1 картинке, то я решил поменять цвет кнопок, шесеренку тоже изменил

**Comment by Quod6** [comment]
PS светло-оранцевый цвет на картинке - на самом деле желтый как на кнопках

**Comment by Quod6** [comment]
![image](https://user-images.githubusercontent.com/36698256/141702872-c5e952f3-1b6d-45d1-b80a-d49ec1e92eb6.png)

на сколько потянет от 0 до 10

**Comment by Quod6** [comment]
![image](https://user-images.githubusercontent.com/36698256/141703514-32c51518-d512-4f9b-a74e-88a1493d5fe6.png)

поменял желтый на оранжевый, вроде лучше

**Comment by Quod6** [comment]
![image](https://user-images.githubusercontent.com/36698256/141703792-850a015a-5feb-42b1-9c3a-e36b69b0a588.png)

v3

**Comment by CitizenFourCF4** [comment]
В итоге, в какой цветовой гамме мы работаем?
В желтой или оранжевой?

**Comment by Dmitriyyolo** [comment]
![newmap](https://user-images.githubusercontent.com/55884664/147393631-fd444d7c-6104-49e6-9ce9-622831720040.png)

**Comment by Dmitriyyolo** [comment]
![newmap2](https://user-images.githubusercontent.com/55884664/147394078-322ceaa3-16ff-42aa-a213-5f9aff4e12d7.png)
